apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rhu4zw3cd-go 
  janus-idp.io/tekton: rhu4zw3cd-go
  backstage.io/kubernetes-id: rhu4zw3cd-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rhu4zw3cd-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml