apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rhu4zw3cd-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhu4zw3cd-go 
  name: rhu4zw3cd-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rhu4zw3cd-go 
